import {
  Globe, Link2, BookOpen, Brain, FileText, Cloud, Bot, LayoutGrid,
  Code, Music, Youtube, Video, Calculator, Search, Star, GraduationCap,
  Laptop, Mail, Calendar, Clipboard, FlaskConical, Headphones, Coffee,
  Sigma, Newspaper, Map, Image, Mic, Folder, Database, Bookmark,
  MessageCircle, Gamepad2, Palette, ShoppingCart, Tv, Plane,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

export const ICON_MAP: Record<string, LucideIcon> = {
  Globe, Link2, BookOpen, Brain, FileText, Cloud, Bot, LayoutGrid,
  Code, Music, Youtube, Video, Calculator, Search, Star, GraduationCap,
  Laptop, Mail, Calendar, Clipboard, FlaskConical, Headphones, Coffee,
  Sigma, Newspaper, Map, Image, Mic, Folder, Database, Bookmark,
  MessageCircle, Gamepad2, Palette, ShoppingCart, Tv, Plane,
};

export const ICON_OPTIONS: { key: string; Icon: LucideIcon; label: string }[] = [
  { key: "Globe",          Icon: Globe,          label: "Globe" },
  { key: "Link2",          Icon: Link2,           label: "Link" },
  { key: "BookOpen",       Icon: BookOpen,        label: "Book" },
  { key: "Brain",          Icon: Brain,           label: "Brain / AI" },
  { key: "Bot",            Icon: Bot,             label: "Bot / AI" },
  { key: "GraduationCap",  Icon: GraduationCap,   label: "School" },
  { key: "FileText",       Icon: FileText,        label: "Document" },
  { key: "Clipboard",      Icon: Clipboard,       label: "Clipboard" },
  { key: "Folder",         Icon: Folder,          label: "Folder" },
  { key: "Cloud",          Icon: Cloud,           label: "Cloud Drive" },
  { key: "Database",       Icon: Database,        label: "Database" },
  { key: "LayoutGrid",     Icon: LayoutGrid,      label: "Dashboard" },
  { key: "Laptop",         Icon: Laptop,          label: "Laptop" },
  { key: "Code",           Icon: Code,            label: "Code" },
  { key: "Calculator",     Icon: Calculator,      label: "Calculator" },
  { key: "Sigma",          Icon: Sigma,           label: "Maths" },
  { key: "FlaskConical",   Icon: FlaskConical,    label: "Science" },
  { key: "Map",            Icon: Map,             label: "Map" },
  { key: "Newspaper",      Icon: Newspaper,       label: "News" },
  { key: "Search",         Icon: Search,          label: "Search" },
  { key: "Youtube",        Icon: Youtube,         label: "YouTube" },
  { key: "Video",          Icon: Video,           label: "Video" },
  { key: "Tv",             Icon: Tv,              label: "TV" },
  { key: "Music",          Icon: Music,           label: "Music" },
  { key: "Headphones",     Icon: Headphones,      label: "Headphones" },
  { key: "Mic",            Icon: Mic,             label: "Microphone" },
  { key: "Mail",           Icon: Mail,            label: "Email" },
  { key: "MessageCircle",  Icon: MessageCircle,   label: "Chat" },
  { key: "Calendar",       Icon: Calendar,        label: "Calendar" },
  { key: "Star",           Icon: Star,            label: "Starred" },
  { key: "Bookmark",       Icon: Bookmark,        label: "Bookmark" },
  { key: "Image",          Icon: Image,           label: "Image" },
  { key: "Palette",        Icon: Palette,         label: "Art / Design" },
  { key: "Coffee",         Icon: Coffee,          label: "Coffee" },
  { key: "Gamepad2",       Icon: Gamepad2,        label: "Games" },
  { key: "Plane",          Icon: Plane,           label: "Travel" },
  { key: "ShoppingCart",   Icon: ShoppingCart,    label: "Shopping" },
];
