import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'en' | 'es' | 'fr' | 'de' | 'pt' | 'it' | 'ja' | 'ko' | 'zh';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    // Header
    'app.title': 'StudyFlow',
    'app.subtitle': 'AI-Powered Student Productivity',
    'header.studyMode': 'Study Mode',
    'header.signIn': 'Sign In',
    'header.signOut': 'Sign Out',
    'header.overdue': 'overdue',
    'header.dueToday': 'due today',
    
    // Main sections
    'section.tasks': 'Tasks',
    'section.progress': 'Progress',
    'section.timer': 'Focus Timer',
    'section.studyLinks': 'Study Links',
    'section.quickNotes': 'Quick Notes',
    'section.prioritization': 'Task Prioritization',
    
    // Common actions
    'action.add': 'Add',
    'action.edit': 'Edit',
    'action.delete': 'Delete',
    'action.save': 'Save',
    'action.cancel': 'Cancel',
    'action.complete': 'Complete',
    'action.start': 'Start',
    'action.pause': 'Pause',
    'action.stop': 'Stop',
    'action.reset': 'Reset',
    
    // Task related
    'task.new': 'New Task',
    'task.title': 'Task Title',
    'task.description': 'Description',
    'task.priority': 'Priority',
    'task.dueDate': 'Due Date',
    'task.completed': 'Completed',
    'task.pending': 'Pending',
    'task.high': 'High',
    'task.medium': 'Medium',
    'task.low': 'Low',
    'task.addTask': 'Add Task',
    'task.noTasks': 'No tasks yet',
    'task.createFirst': 'Create your first task to get started!',
    'task.overdue': 'Overdue',
    'task.today': 'Due Today',
    'task.upcoming': 'Upcoming',
    'task.completed.title': 'Completed Tasks',
    'task.markComplete': 'Mark as Complete',
    'task.markIncomplete': 'Mark as Incomplete',
    'task.edit': 'Edit Task',
    'task.delete': 'Delete Task',
    'task.due': 'Due',
    'task.noDueDate': 'No due date',
    
    // Focus Timer
    'timer.title': 'Focus Timer',
    'timer.selectSession': 'Select a session',
    'timer.homework': 'Homework',
    'timer.study': 'Study',
    'timer.break': 'Break',
    'timer.reading': 'Reading',
    'timer.writing': 'Writing',
    'timer.research': 'Research',
    'timer.review': 'Review',
    'timer.minutes': 'minutes',
    'timer.seconds': 'seconds',
    'timer.timeUp': 'Time\'s up!',
    'timer.sessionComplete': 'Session complete!',
    'timer.takeBreak': 'Take a break',
    'timer.backToWork': 'Back to work',
    'timer.paused': 'Paused',
    'timer.resume': 'Resume',
    
    // Progress Tracker
    'progress.title': 'Progress Tracker',
    'progress.tasksCompleted': 'Tasks Completed',
    'progress.totalTasks': 'Total Tasks',
    'progress.completionRate': 'Completion Rate',
    'progress.studyTime': 'Study Time',
    'progress.thisWeek': 'This Week',
    'progress.thisMonth': 'This Month',
    'progress.hours': 'hours',
    'progress.noData': 'No data available',
    'progress.keepGoing': 'Keep up the great work!',
    
    // Quick Notes
    'notes.title': 'Quick Notes',
    'notes.add': 'Add Note',
    'notes.placeholder': 'Start typing your note...',
    'notes.save': 'Save Note',
    'notes.edit': 'Edit Note',
    'notes.delete': 'Delete Note',
    'notes.empty': 'No notes yet',
    'notes.createFirst': 'Create your first note!',
    'notes.untitled': 'Untitled Note',
    'notes.confirmDelete': 'Are you sure you want to delete this note?',
    'notes.deleteConfirm': 'This action cannot be undone.',
    
    // Study Links
    'links.title': 'Study Links',
    'links.add': 'Add Link',
    'links.name': 'Link Name',
    'links.url': 'URL',
    'links.category': 'Category',
    'links.research': 'Research',
    'links.reference': 'Reference',
    'links.tutorial': 'Tutorial',
    'links.article': 'Article',
    'links.video': 'Video',
    'links.other': 'Other',
    'links.visit': 'Visit Link',
    'links.edit': 'Edit Link',
    'links.delete': 'Delete Link',
    'links.empty': 'No study links yet',
    'links.createFirst': 'Add your first study link!',
    
    // Task Prioritization
    'prioritization.title': 'Task Prioritization',
    'prioritization.dragToReorder': 'Drag tasks to reorder by priority',
    'prioritization.highPriority': 'High Priority',
    'prioritization.mediumPriority': 'Medium Priority',
    'prioritization.lowPriority': 'Low Priority',
    'prioritization.reorderTasks': 'Reorder Tasks',
    'prioritization.empty': 'No tasks to prioritize',
    'prioritization.createTasks': 'Create some tasks first!',
    
    // Study Mode
    'study.title': 'Study Mode',
    'study.focusMode': 'Focus Mode Active',
    'study.exitFocus': 'Exit Focus Mode',
    'study.currentTask': 'Current Task',
    'study.noActiveTask': 'No active task',
    'study.selectTask': 'Select a task to focus on',
    'study.timeRemaining': 'Time Remaining',
    'study.sessionType': 'Session Type',
    'study.productivity': 'Productivity Dashboard',
    'study.todaysFocus': 'Today\'s Focus',
    'study.weeklyGoal': 'Weekly Goal',
    'study.completedToday': 'Completed Today',
    'study.streak': 'Current Streak',
    'study.days': 'days',
    
    // AI Study Suggestions
    'ai.title': 'AI Study Suggestions',
    'ai.generating': 'Generating suggestions...',
    'ai.suggestions': 'Study Suggestions',
    'ai.noSuggestions': 'No suggestions available',
    'ai.tryAgain': 'Try again',
    'ai.basedOnTasks': 'Based on your current tasks',
    'ai.studyPlan': 'Study Plan',
    'ai.recommendation': 'Recommendation',
    
    // Forms and Dialogs
    'form.required': 'This field is required',
    'form.cancel': 'Cancel',
    'form.save': 'Save',
    'form.create': 'Create',
    'form.update': 'Update',
    'form.delete': 'Delete',
    'form.confirm': 'Confirm',
    'form.loading': 'Loading...',
    'form.success': 'Success!',
    'form.error': 'Error occurred',
    'form.tryAgain': 'Try again',
    
    // General
    'general.loading': 'Loading...',
    'general.error': 'Error',
    'general.success': 'Success',
    'general.warning': 'Warning',
    'general.info': 'Info',
    'general.close': 'Close',
    'general.open': 'Open',
    'general.show': 'Show',
    'general.hide': 'Hide',
    'general.more': 'More',
    'general.less': 'Less',
    'general.all': 'All',
    'general.none': 'None',
    'general.search': 'Search',
    'general.filter': 'Filter',
    'general.sort': 'Sort',
    'general.refresh': 'Refresh',
  },
  es: {
    // Header
    'app.title': 'StudyFlow',
    'app.subtitle': 'Productividad Estudiantil con IA',
    'header.studyMode': 'Modo Estudio',
    'header.signIn': 'Iniciar Sesión',
    'header.signOut': 'Cerrar Sesión',
    'header.overdue': 'vencido',
    'header.dueToday': 'vence hoy',
    
    // Main sections
    'section.tasks': 'Tareas',
    'section.progress': 'Progreso',
    'section.timer': 'Temporizador de Enfoque',
    'section.studyLinks': 'Enlaces de Estudio',
    'section.quickNotes': 'Notas Rápidas',
    'section.prioritization': 'Priorización de Tareas',
    
    // Common actions
    'action.add': 'Agregar',
    'action.edit': 'Editar',
    'action.delete': 'Eliminar',
    'action.save': 'Guardar',
    'action.cancel': 'Cancelar',
    'action.complete': 'Completar',
    'action.start': 'Iniciar',
    'action.pause': 'Pausar',
    'action.stop': 'Detener',
    'action.reset': 'Reiniciar',
    
    // Task related
    'task.new': 'Nueva Tarea',
    'task.title': 'Título de Tarea',
    'task.description': 'Descripción',
    'task.priority': 'Prioridad',
    'task.dueDate': 'Fecha de Vencimiento',
    'task.completed': 'Completada',
    'task.pending': 'Pendiente',
    'task.high': 'Alta',
    'task.medium': 'Media',
    'task.low': 'Baja',
    'task.addTask': 'Agregar Tarea',
    'task.noTasks': 'No hay tareas aún',
    'task.createFirst': '¡Crea tu primera tarea para comenzar!',
    'task.overdue': 'Vencida',
    'task.today': 'Vence Hoy',
    'task.upcoming': 'Próxima',
    'task.completed.title': 'Tareas Completadas',
    'task.markComplete': 'Marcar como Completada',
    'task.markIncomplete': 'Marcar como Incompleta',
    'task.edit': 'Editar Tarea',
    'task.delete': 'Eliminar Tarea',
    'task.due': 'Vence',
    'task.noDueDate': 'Sin fecha de vencimiento',
    
    // Focus Timer
    'timer.title': 'Temporizador de Enfoque',
    'timer.selectSession': 'Seleccionar una sesión',
    'timer.homework': 'Tarea',
    'timer.study': 'Estudio',
    'timer.break': 'Descanso',
    'timer.reading': 'Lectura',
    'timer.writing': 'Escritura',
    'timer.research': 'Investigación',
    'timer.review': 'Revisión',
    'timer.minutes': 'minutos',
    'timer.seconds': 'segundos',
    'timer.timeUp': '¡Se acabó el tiempo!',
    'timer.sessionComplete': '¡Sesión completada!',
    'timer.takeBreak': 'Toma un descanso',
    'timer.backToWork': 'Volver al trabajo',
    'timer.paused': 'Pausado',
    'timer.resume': 'Reanudar',
    
    // Progress Tracker
    'progress.title': 'Seguimiento de Progreso',
    'progress.tasksCompleted': 'Tareas Completadas',
    'progress.totalTasks': 'Tareas Totales',
    'progress.completionRate': 'Tasa de Finalización',
    'progress.studyTime': 'Tiempo de Estudio',
    'progress.thisWeek': 'Esta Semana',
    'progress.thisMonth': 'Este Mes',
    'progress.hours': 'horas',
    'progress.noData': 'No hay datos disponibles',
    'progress.keepGoing': '¡Sigue así!',
    
    // Quick Notes
    'notes.title': 'Notas Rápidas',
    'notes.add': 'Agregar Nota',
    'notes.placeholder': 'Comienza a escribir tu nota...',
    'notes.save': 'Guardar Nota',
    'notes.edit': 'Editar Nota',
    'notes.delete': 'Eliminar Nota',
    'notes.empty': 'No hay notas aún',
    'notes.createFirst': '¡Crea tu primera nota!',
    'notes.untitled': 'Nota Sin Título',
    'notes.confirmDelete': '¿Estás seguro de que quieres eliminar esta nota?',
    'notes.deleteConfirm': 'Esta acción no se puede deshacer.',
    
    // Study Links
    'links.title': 'Enlaces de Estudio',
    'links.add': 'Agregar Enlace',
    'links.name': 'Nombre del Enlace',
    'links.url': 'URL',
    'links.category': 'Categoría',
    'links.research': 'Investigación',
    'links.reference': 'Referencia',
    'links.tutorial': 'Tutorial',
    'links.article': 'Artículo',
    'links.video': 'Video',
    'links.other': 'Otro',
    'links.visit': 'Visitar Enlace',
    'links.edit': 'Editar Enlace',
    'links.delete': 'Eliminar Enlace',
    'links.empty': 'No hay enlaces de estudio aún',
    'links.createFirst': '¡Agrega tu primer enlace de estudio!',
    
    // Task Prioritization
    'prioritization.title': 'Priorización de Tareas',
    'prioritization.dragToReorder': 'Arrastra las tareas para reordenar por prioridad',
    'prioritization.highPriority': 'Alta Prioridad',
    'prioritization.mediumPriority': 'Prioridad Media',
    'prioritization.lowPriority': 'Baja Prioridad',
    'prioritization.reorderTasks': 'Reordenar Tareas',
    'prioritization.empty': 'No hay tareas para priorizar',
    'prioritization.createTasks': '¡Crea algunas tareas primero!',
    
    // Study Mode
    'study.title': 'Modo Estudio',
    'study.focusMode': 'Modo Enfoque Activo',
    'study.exitFocus': 'Salir del Modo Enfoque',
    'study.currentTask': 'Tarea Actual',
    'study.noActiveTask': 'No hay tarea activa',
    'study.selectTask': 'Selecciona una tarea para enfocarte',
    'study.timeRemaining': 'Tiempo Restante',
    'study.sessionType': 'Tipo de Sesión',
    'study.productivity': 'Panel de Productividad',
    'study.todaysFocus': 'Enfoque de Hoy',
    'study.weeklyGoal': 'Meta Semanal',
    'study.completedToday': 'Completado Hoy',
    'study.streak': 'Racha Actual',
    'study.days': 'días',
    
    // AI Study Suggestions
    'ai.title': 'Sugerencias de Estudio IA',
    'ai.generating': 'Generando sugerencias...',
    'ai.suggestions': 'Sugerencias de Estudio',
    'ai.noSuggestions': 'No hay sugerencias disponibles',
    'ai.tryAgain': 'Intentar de nuevo',
    'ai.basedOnTasks': 'Basado en tus tareas actuales',
    'ai.studyPlan': 'Plan de Estudio',
    'ai.recommendation': 'Recomendación',
    
    // Forms and Dialogs
    'form.required': 'Este campo es obligatorio',
    'form.cancel': 'Cancelar',
    'form.save': 'Guardar',
    'form.create': 'Crear',
    'form.update': 'Actualizar',
    'form.delete': 'Eliminar',
    'form.confirm': 'Confirmar',
    'form.loading': 'Cargando...',
    'form.success': '¡Éxito!',
    'form.error': 'Ocurrió un error',
    'form.tryAgain': 'Intentar de nuevo',
    
    // General
    'general.loading': 'Cargando...',
    'general.error': 'Error',
    'general.success': 'Éxito',
    'general.warning': 'Advertencia',
    'general.info': 'Información',
    'general.close': 'Cerrar',
    'general.open': 'Abrir',
    'general.show': 'Mostrar',
    'general.hide': 'Ocultar',
    'general.more': 'Más',
    'general.less': 'Menos',
    'general.all': 'Todo',
    'general.none': 'Ninguno',
    'general.search': 'Buscar',
    'general.filter': 'Filtrar',
    'general.sort': 'Ordenar',
    'general.refresh': 'Actualizar',
  },
  fr: {
    // Header
    'app.title': 'StudyFlow',
    'app.subtitle': 'Productivité Étudiante Alimentée par IA',
    'header.studyMode': 'Mode Étude',
    'header.signIn': 'Se Connecter',
    'header.signOut': 'Se Déconnecter',
    'header.overdue': 'en retard',
    'header.dueToday': 'dû aujourd\'hui',
    
    // Main sections
    'section.tasks': 'Tâches',
    'section.progress': 'Progrès',
    'section.timer': 'Minuteur de Focus',
    'section.studyLinks': 'Liens d\'Étude',
    'section.quickNotes': 'Notes Rapides',
    'section.prioritization': 'Priorisation des Tâches',
    
    // Common actions
    'action.add': 'Ajouter',
    'action.edit': 'Modifier',
    'action.delete': 'Supprimer',
    'action.save': 'Sauvegarder',
    'action.cancel': 'Annuler',
    'action.complete': 'Terminer',
    'action.start': 'Démarrer',
    'action.pause': 'Pause',
    'action.stop': 'Arrêter',
    'action.reset': 'Réinitialiser',
    
    // Task related
    'task.new': 'Nouvelle Tâche',
    'task.title': 'Titre de Tâche',
    'task.description': 'Description',
    'task.priority': 'Priorité',
    'task.dueDate': 'Date d\'Échéance',
    'task.completed': 'Terminée',
    'task.pending': 'En Attente',
    'task.high': 'Haute',
    'task.medium': 'Moyenne',
    'task.low': 'Basse',
    'task.addTask': 'Ajouter Tâche',
    'task.noTasks': 'Aucune tâche encore',
    'task.createFirst': 'Créez votre première tâche pour commencer!',
    'task.overdue': 'En Retard',
    'task.today': 'Dû Aujourd\'hui',
    'task.upcoming': 'À Venir',
    'task.completed.title': 'Tâches Terminées',
    'task.markComplete': 'Marquer comme Terminée',
    'task.markIncomplete': 'Marquer comme Incomplète',
    'task.edit': 'Modifier Tâche',
    'task.delete': 'Supprimer Tâche',
    'task.due': 'Dû',
    'task.noDueDate': 'Pas de date d\'échéance',
    
    // Focus Timer
    'timer.title': 'Minuteur de Focus',
    'timer.selectSession': 'Sélectionner une session',
    'timer.homework': 'Devoirs',
    'timer.study': 'Étude',
    'timer.break': 'Pause',
    'timer.reading': 'Lecture',
    'timer.writing': 'Écriture',
    'timer.research': 'Recherche',
    'timer.review': 'Révision',
    'timer.minutes': 'minutes',
    'timer.seconds': 'secondes',
    'timer.timeUp': 'Temps écoulé!',
    'timer.sessionComplete': 'Session terminée!',
    'timer.takeBreak': 'Prenez une pause',
    'timer.backToWork': 'Retour au travail',
    'timer.paused': 'En Pause',
    'timer.resume': 'Reprendre',
    
    // Progress Tracker
    'progress.title': 'Suivi des Progrès',
    'progress.tasksCompleted': 'Tâches Terminées',
    'progress.totalTasks': 'Tâches Totales',
    'progress.completionRate': 'Taux de Completion',
    'progress.studyTime': 'Temps d\'Étude',
    'progress.thisWeek': 'Cette Semaine',
    'progress.thisMonth': 'Ce Mois',
    'progress.hours': 'heures',
    'progress.noData': 'Aucune donnée disponible',
    'progress.keepGoing': 'Continuez comme ça!',
    
    // Quick Notes
    'notes.title': 'Notes Rapides',
    'notes.add': 'Ajouter Note',
    'notes.placeholder': 'Commencez à taper votre note...',
    'notes.save': 'Sauvegarder Note',
    'notes.edit': 'Modifier Note',
    'notes.delete': 'Supprimer Note',
    'notes.empty': 'Aucune note encore',
    'notes.createFirst': 'Créez votre première note!',
    'notes.untitled': 'Note Sans Titre',
    'notes.confirmDelete': 'Êtes-vous sûr de vouloir supprimer cette note?',
    'notes.deleteConfirm': 'Cette action ne peut pas être annulée.',
    
    // Study Links
    'links.title': 'Liens d\'Étude',
    'links.add': 'Ajouter Lien',
    'links.name': 'Nom du Lien',
    'links.url': 'URL',
    'links.category': 'Catégorie',
    'links.research': 'Recherche',
    'links.reference': 'Référence',
    'links.tutorial': 'Tutoriel',
    'links.article': 'Article',
    'links.video': 'Vidéo',
    'links.other': 'Autre',
    'links.visit': 'Visiter Lien',
    'links.edit': 'Modifier Lien',
    'links.delete': 'Supprimer Lien',
    'links.empty': 'Aucun lien d\'étude encore',
    'links.createFirst': 'Ajoutez votre premier lien d\'étude!',
    
    // Task Prioritization
    'prioritization.title': 'Priorisation des Tâches',
    'prioritization.dragToReorder': 'Glissez les tâches pour réorganiser par priorité',
    'prioritization.highPriority': 'Haute Priorité',
    'prioritization.mediumPriority': 'Priorité Moyenne',
    'prioritization.lowPriority': 'Basse Priorité',
    'prioritization.reorderTasks': 'Réorganiser Tâches',
    'prioritization.empty': 'Aucune tâche à prioriser',
    'prioritization.createTasks': 'Créez d\'abord quelques tâches!',
    
    // Study Mode
    'study.title': 'Mode Étude',
    'study.focusMode': 'Mode Focus Actif',
    'study.exitFocus': 'Quitter Mode Focus',
    'study.currentTask': 'Tâche Actuelle',
    'study.noActiveTask': 'Aucune tâche active',
    'study.selectTask': 'Sélectionnez une tâche pour vous concentrer',
    'study.timeRemaining': 'Temps Restant',
    'study.sessionType': 'Type de Session',
    'study.productivity': 'Tableau de Productivité',
    'study.todaysFocus': 'Focus d\'Aujourd\'hui',
    'study.weeklyGoal': 'Objectif Hebdomadaire',
    'study.completedToday': 'Terminé Aujourd\'hui',
    'study.streak': 'Série Actuelle',
    'study.days': 'jours',
    
    // AI Study Suggestions
    'ai.title': 'Suggestions d\'Étude IA',
    'ai.generating': 'Génération de suggestions...',
    'ai.suggestions': 'Suggestions d\'Étude',
    'ai.noSuggestions': 'Aucune suggestion disponible',
    'ai.tryAgain': 'Essayer à nouveau',
    'ai.basedOnTasks': 'Basé sur vos tâches actuelles',
    'ai.studyPlan': 'Plan d\'Étude',
    'ai.recommendation': 'Recommandation',
    
    // Forms and Dialogs
    'form.required': 'Ce champ est requis',
    'form.cancel': 'Annuler',
    'form.save': 'Sauvegarder',
    'form.create': 'Créer',
    'form.update': 'Mettre à jour',
    'form.delete': 'Supprimer',
    'form.confirm': 'Confirmer',
    'form.loading': 'Chargement...',
    'form.success': 'Succès!',
    'form.error': 'Erreur survenue',
    'form.tryAgain': 'Essayer à nouveau',
    
    // General
    'general.loading': 'Chargement...',
    'general.error': 'Erreur',
    'general.success': 'Succès',
    'general.warning': 'Avertissement',
    'general.info': 'Info',
    'general.close': 'Fermer',
    'general.open': 'Ouvrir',
    'general.show': 'Afficher',
    'general.hide': 'Cacher',
    'general.more': 'Plus',
    'general.less': 'Moins',
    'general.all': 'Tout',
    'general.none': 'Aucun',
    'general.search': 'Rechercher',
    'general.filter': 'Filtrer',
    'general.sort': 'Trier',
    'general.refresh': 'Actualiser',
  },
  de: {
    // Header
    'app.title': 'StudyFlow',
    'app.subtitle': 'KI-gestützte Studentenproduktivität',
    'header.studyMode': 'Lernmodus',
    'header.signIn': 'Anmelden',
    'header.signOut': 'Abmelden',
    'header.overdue': 'überfällig',
    'header.dueToday': 'heute fällig',
    
    // Main sections
    'section.tasks': 'Aufgaben',
    'section.progress': 'Fortschritt',
    'section.timer': 'Fokus-Timer',
    'section.studyLinks': 'Lernlinks',
    'section.quickNotes': 'Schnelle Notizen',
    'section.prioritization': 'Aufgabenpriorisierung',
    
    // Common actions
    'action.add': 'Hinzufügen',
    'action.edit': 'Bearbeiten',
    'action.delete': 'Löschen',
    'action.save': 'Speichern',
    'action.cancel': 'Abbrechen',
    'action.complete': 'Abschließen',
    'action.start': 'Starten',
    'action.pause': 'Pausieren',
    'action.stop': 'Stoppen',
    'action.reset': 'Zurücksetzen',
    
    // Task related
    'task.new': 'Neue Aufgabe',
    'task.title': 'Aufgabentitel',
    'task.description': 'Beschreibung',
    'task.priority': 'Priorität',
    'task.dueDate': 'Fälligkeitsdatum',
    'task.completed': 'Abgeschlossen',
    'task.pending': 'Ausstehend',
    'task.high': 'Hoch',
    'task.medium': 'Mittel',
    'task.low': 'Niedrig',
    'task.addTask': 'Aufgabe hinzufügen',
    'task.noTasks': 'Noch keine Aufgaben',
    'task.createFirst': 'Erstelle deine erste Aufgabe um zu beginnen!',
    'task.overdue': 'Überfällig',
    'task.today': 'Heute fällig',
    'task.upcoming': 'Anstehend',
    'task.completed.title': 'Abgeschlossene Aufgaben',
    'task.markComplete': 'Als abgeschlossen markieren',
    'task.markIncomplete': 'Als unvollständig markieren',
    'task.edit': 'Aufgabe bearbeiten',
    'task.delete': 'Aufgabe löschen',
    'task.due': 'Fällig',
    'task.noDueDate': 'Kein Fälligkeitsdatum',
    
    // Focus Timer
    'timer.title': 'Fokus-Timer',
    'timer.selectSession': 'Sitzung auswählen',
    'timer.homework': 'Hausaufgaben',
    'timer.study': 'Lernen',
    'timer.break': 'Pause',
    'timer.reading': 'Lesen',
    'timer.writing': 'Schreiben',
    'timer.research': 'Recherche',
    'timer.review': 'Wiederholung',
    'timer.minutes': 'Minuten',
    'timer.seconds': 'Sekunden',
    'timer.timeUp': 'Zeit ist um!',
    'timer.sessionComplete': 'Sitzung beendet!',
    'timer.takeBreak': 'Mach eine Pause',
    'timer.backToWork': 'Zurück zur Arbeit',
    'timer.paused': 'Pausiert',
    'timer.resume': 'Fortsetzen',
    
    // Progress Tracker
    'progress.title': 'Fortschrittsverfolger',
    'progress.tasksCompleted': 'Aufgaben abgeschlossen',
    'progress.totalTasks': 'Gesamtaufgaben',
    'progress.completionRate': 'Abschlussrate',
    'progress.studyTime': 'Lernzeit',
    'progress.thisWeek': 'Diese Woche',
    'progress.thisMonth': 'Diesen Monat',
    'progress.hours': 'Stunden',
    'progress.noData': 'Keine Daten verfügbar',
    'progress.keepGoing': 'Weiter so!',
    
    // Quick Notes
    'notes.title': 'Schnelle Notizen',
    'notes.add': 'Notiz hinzufügen',
    'notes.placeholder': 'Beginne deine Notiz zu schreiben...',
    'notes.save': 'Notiz speichern',
    'notes.edit': 'Notiz bearbeiten',
    'notes.delete': 'Notiz löschen',
    'notes.empty': 'Noch keine Notizen',
    'notes.createFirst': 'Erstelle deine erste Notiz!',
    'notes.untitled': 'Unbenannte Notiz',
    'notes.confirmDelete': 'Bist du sicher, dass du diese Notiz löschen möchtest?',
    'notes.deleteConfirm': 'Diese Aktion kann nicht rückgängig gemacht werden.',
    
    // Study Links
    'links.title': 'Lernlinks',
    'links.add': 'Link hinzufügen',
    'links.name': 'Link-Name',
    'links.url': 'URL',
    'links.category': 'Kategorie',
    'links.research': 'Forschung',
    'links.reference': 'Referenz',
    'links.tutorial': 'Tutorial',
    'links.article': 'Artikel',
    'links.video': 'Video',
    'links.other': 'Andere',
    'links.visit': 'Link besuchen',
    'links.edit': 'Link bearbeiten',
    'links.delete': 'Link löschen',
    'links.empty': 'Noch keine Lernlinks',
    'links.createFirst': 'Füge deinen ersten Lernlink hinzu!',
    
    // Task Prioritization
    'prioritization.title': 'Aufgabenpriorisierung',
    'prioritization.dragToReorder': 'Ziehe Aufgaben zur Neuordnung nach Priorität',
    'prioritization.highPriority': 'Hohe Priorität',
    'prioritization.mediumPriority': 'Mittlere Priorität',
    'prioritization.lowPriority': 'Niedrige Priorität',
    'prioritization.reorderTasks': 'Aufgaben neu ordnen',
    'prioritization.empty': 'Keine Aufgaben zu priorisieren',
    'prioritization.createTasks': 'Erstelle zuerst einige Aufgaben!',
    
    // Study Mode
    'study.title': 'Lernmodus',
    'study.focusMode': 'Fokus-Modus aktiv',
    'study.exitFocus': 'Fokus-Modus verlassen',
    'study.currentTask': 'Aktuelle Aufgabe',
    'study.noActiveTask': 'Keine aktive Aufgabe',
    'study.selectTask': 'Wähle eine Aufgabe zum Fokussieren',
    'study.timeRemaining': 'Verbleibende Zeit',
    'study.sessionType': 'Sitzungstyp',
    'study.productivity': 'Produktivitäts-Dashboard',
    'study.todaysFocus': 'Heutiger Fokus',
    'study.weeklyGoal': 'Wochenziel',
    'study.completedToday': 'Heute abgeschlossen',
    'study.streak': 'Aktuelle Serie',
    'study.days': 'Tage',
    
    // AI Study Suggestions
    'ai.title': 'KI-Lernvorschläge',
    'ai.generating': 'Generiere Vorschläge...',
    'ai.suggestions': 'Lernvorschläge',
    'ai.noSuggestions': 'Keine Vorschläge verfügbar',
    'ai.tryAgain': 'Erneut versuchen',
    'ai.basedOnTasks': 'Basierend auf deinen aktuellen Aufgaben',
    'ai.studyPlan': 'Lernplan',
    'ai.recommendation': 'Empfehlung',
    
    // Forms and Dialogs
    'form.required': 'Dieses Feld ist erforderlich',
    'form.cancel': 'Abbrechen',
    'form.save': 'Speichern',
    'form.create': 'Erstellen',
    'form.update': 'Aktualisieren',
    'form.delete': 'Löschen',
    'form.confirm': 'Bestätigen',
    'form.loading': 'Laden...',
    'form.success': 'Erfolgreich!',
    'form.error': 'Fehler aufgetreten',
    'form.tryAgain': 'Erneut versuchen',
    
    // General
    'general.loading': 'Laden...',
    'general.error': 'Fehler',
    'general.success': 'Erfolg',
    'general.warning': 'Warnung',
    'general.info': 'Info',
    'general.close': 'Schließen',
    'general.open': 'Öffnen',
    'general.show': 'Anzeigen',
    'general.hide': 'Verbergen',
    'general.more': 'Mehr',
    'general.less': 'Weniger',
    'general.all': 'Alle',
    'general.none': 'Keine',
    'general.search': 'Suchen',
    'general.filter': 'Filtern',
    'general.sort': 'Sortieren',
    'general.refresh': 'Aktualisieren',
  },
  pt: {
    // Header
    'app.title': 'StudyFlow',
    'app.subtitle': 'Produtividade Estudantil com IA',
    'header.studyMode': 'Modo Estudo',
    'header.signIn': 'Entrar',
    'header.signOut': 'Sair',
    'header.overdue': 'atrasado',
    'header.dueToday': 'vence hoje',
    
    // Main sections
    'section.tasks': 'Tarefas',
    'section.progress': 'Progresso',
    'section.timer': 'Timer de Foco',
    'section.studyLinks': 'Links de Estudo',
    'section.quickNotes': 'Notas Rápidas',
    'section.prioritization': 'Priorização de Tarefas',
    
    // Common actions
    'action.add': 'Adicionar',
    'action.edit': 'Editar',
    'action.delete': 'Excluir',
    'action.save': 'Salvar',
    'action.cancel': 'Cancelar',
    'action.complete': 'Completar',
    'action.start': 'Iniciar',
    'action.pause': 'Pausar',
    'action.stop': 'Parar',
    'action.reset': 'Reiniciar',
    
    // Task related
    'task.new': 'Nova Tarefa',
    'task.title': 'Título da Tarefa',
    'task.description': 'Descrição',
    'task.priority': 'Prioridade',
    'task.dueDate': 'Data de Vencimento',
    'task.completed': 'Concluída',
    'task.pending': 'Pendente',
    'task.high': 'Alta',
    'task.medium': 'Média',
    'task.low': 'Baixa',
    'task.addTask': 'Adicionar Tarefa',
    'task.noTasks': 'Nenhuma tarefa ainda',
    'task.createFirst': 'Crie sua primeira tarefa para começar!',
    'task.overdue': 'Atrasada',
    'task.today': 'Vence Hoje',
    'task.upcoming': 'Próxima',
    'task.completed.title': 'Tarefas Concluídas',
    'task.markComplete': 'Marcar como Concluída',
    'task.markIncomplete': 'Marcar como Incompleta',
    'task.edit': 'Editar Tarefa',
    'task.delete': 'Excluir Tarefa',
    'task.due': 'Vence',
    'task.noDueDate': 'Sem data de vencimento',
    
    // Focus Timer
    'timer.title': 'Timer de Foco',
    'timer.selectSession': 'Selecionar uma sessão',
    'timer.homework': 'Dever de Casa',
    'timer.study': 'Estudo',
    'timer.break': 'Pausa',
    'timer.reading': 'Leitura',
    'timer.writing': 'Escrita',
    'timer.research': 'Pesquisa',
    'timer.review': 'Revisão',
    'timer.minutes': 'minutos',
    'timer.seconds': 'segundos',
    'timer.timeUp': 'Tempo esgotado!',
    'timer.sessionComplete': 'Sessão concluída!',
    'timer.takeBreak': 'Faça uma pausa',
    'timer.backToWork': 'Voltar ao trabalho',
    'timer.paused': 'Pausado',
    'timer.resume': 'Retomar',
    
    // Progress Tracker
    'progress.title': 'Rastreador de Progresso',
    'progress.tasksCompleted': 'Tarefas Concluídas',
    'progress.totalTasks': 'Tarefas Totais',
    'progress.completionRate': 'Taxa de Conclusão',
    'progress.studyTime': 'Tempo de Estudo',
    'progress.thisWeek': 'Esta Semana',
    'progress.thisMonth': 'Este Mês',
    'progress.hours': 'horas',
    'progress.noData': 'Nenhum dado disponível',
    'progress.keepGoing': 'Continue assim!',
    
    // Quick Notes
    'notes.title': 'Notas Rápidas',
    'notes.add': 'Adicionar Nota',
    'notes.placeholder': 'Comece a digitar sua nota...',
    'notes.save': 'Salvar Nota',
    'notes.edit': 'Editar Nota',
    'notes.delete': 'Excluir Nota',
    'notes.empty': 'Nenhuma nota ainda',
    'notes.createFirst': 'Crie sua primeira nota!',
    'notes.untitled': 'Nota Sem Título',
    'notes.confirmDelete': 'Tem certeza que deseja excluir esta nota?',
    'notes.deleteConfirm': 'Esta ação não pode ser desfeita.',
    
    // Study Links
    'links.title': 'Links de Estudo',
    'links.add': 'Adicionar Link',
    'links.name': 'Nome do Link',
    'links.url': 'URL',
    'links.category': 'Categoria',
    'links.research': 'Pesquisa',
    'links.reference': 'Referência',
    'links.tutorial': 'Tutorial',
    'links.article': 'Artigo',
    'links.video': 'Vídeo',
    'links.other': 'Outro',
    'links.visit': 'Visitar Link',
    'links.edit': 'Editar Link',
    'links.delete': 'Excluir Link',
    'links.empty': 'Nenhum link de estudo ainda',
    'links.createFirst': 'Adicione seu primeiro link de estudo!',
    
    // Task Prioritization
    'prioritization.title': 'Priorização de Tarefas',
    'prioritization.dragToReorder': 'Arraste tarefas para reordenar por prioridade',
    'prioritization.highPriority': 'Alta Prioridade',
    'prioritization.mediumPriority': 'Prioridade Média',
    'prioritization.lowPriority': 'Baixa Prioridade',
    'prioritization.reorderTasks': 'Reordenar Tarefas',
    'prioritization.empty': 'Nenhuma tarefa para priorizar',
    'prioritization.createTasks': 'Crie algumas tarefas primeiro!',
    
    // Study Mode
    'study.title': 'Modo Estudo',
    'study.focusMode': 'Modo Foco Ativo',
    'study.exitFocus': 'Sair do Modo Foco',
    'study.currentTask': 'Tarefa Atual',
    'study.noActiveTask': 'Nenhuma tarefa ativa',
    'study.selectTask': 'Selecione uma tarefa para focar',
    'study.timeRemaining': 'Tempo Restante',
    'study.sessionType': 'Tipo de Sessão',
    'study.productivity': 'Painel de Produtividade',
    'study.todaysFocus': 'Foco de Hoje',
    'study.weeklyGoal': 'Meta Semanal',
    'study.completedToday': 'Concluído Hoje',
    'study.streak': 'Sequência Atual',
    'study.days': 'dias',
    
    // AI Study Suggestions
    'ai.title': 'Sugestões de Estudo IA',
    'ai.generating': 'Gerando sugestões...',
    'ai.suggestions': 'Sugestões de Estudo',
    'ai.noSuggestions': 'Nenhuma sugestão disponível',
    'ai.tryAgain': 'Tentar novamente',
    'ai.basedOnTasks': 'Baseado em suas tarefas atuais',
    'ai.studyPlan': 'Plano de Estudo',
    'ai.recommendation': 'Recomendação',
    
    // Forms and Dialogs
    'form.required': 'Este campo é obrigatório',
    'form.cancel': 'Cancelar',
    'form.save': 'Salvar',
    'form.create': 'Criar',
    'form.update': 'Atualizar',
    'form.delete': 'Excluir',
    'form.confirm': 'Confirmar',
    'form.loading': 'Carregando...',
    'form.success': 'Sucesso!',
    'form.error': 'Erro ocorreu',
    'form.tryAgain': 'Tentar novamente',
    
    // General
    'general.loading': 'Carregando...',
    'general.error': 'Erro',
    'general.success': 'Sucesso',
    'general.warning': 'Aviso',
    'general.info': 'Informação',
    'general.close': 'Fechar',
    'general.open': 'Abrir',
    'general.show': 'Mostrar',
    'general.hide': 'Ocultar',
    'general.more': 'Mais',
    'general.less': 'Menos',
    'general.all': 'Todos',
    'general.none': 'Nenhum',
    'general.search': 'Pesquisar',
    'general.filter': 'Filtrar',
    'general.sort': 'Ordenar',
    'general.refresh': 'Atualizar',
  },
  it: {
    // Header
    'app.title': 'StudyFlow',
    'app.subtitle': 'Produttività Studentesca Alimentata da IA',
    'header.studyMode': 'Modalità Studio',
    'header.signIn': 'Accedi',
    'header.signOut': 'Esci',
    'header.overdue': 'scaduto',
    'header.dueToday': 'scade oggi',
    
    // Main sections
    'section.tasks': 'Compiti',
    'section.progress': 'Progresso',
    'section.timer': 'Timer di Concentrazione',
    'section.studyLinks': 'Link di Studio',
    'section.quickNotes': 'Note Veloci',
    'section.prioritization': 'Prioritizzazione Compiti',
    
    // Common actions
    'action.add': 'Aggiungi',
    'action.edit': 'Modifica',
    'action.delete': 'Elimina',
    'action.save': 'Salva',
    'action.cancel': 'Annulla',
    'action.complete': 'Completa',
    'action.start': 'Avvia',
    'action.pause': 'Pausa',
    'action.stop': 'Ferma',
    'action.reset': 'Reimposta',
    
    // Task related
    'task.new': 'Nuovo Compito',
    'task.title': 'Titolo Compito',
    'task.description': 'Descrizione',
    'task.priority': 'Priorità',
    'task.dueDate': 'Data di Scadenza',
    'task.completed': 'Completato',
    'task.pending': 'In Attesa',
    'task.high': 'Alta',
    'task.medium': 'Media',
    'task.low': 'Bassa',
    'task.addTask': 'Aggiungi Compito',
    'task.noTasks': 'Nessun compito ancora',
    'task.createFirst': 'Crea il tuo primo compito per iniziare!',
    'task.overdue': 'Scaduto',
    'task.today': 'Scade Oggi',
    'task.upcoming': 'Prossimo',
    'task.completed.title': 'Compiti Completati',
    'task.markComplete': 'Segna come Completato',
    'task.markIncomplete': 'Segna come Incompleto',
    'task.edit': 'Modifica Compito',
    'task.delete': 'Elimina Compito',
    'task.due': 'Scadenza',
    'task.noDueDate': 'Nessuna data di scadenza',
    
    // Focus Timer
    'timer.title': 'Timer di Concentrazione',
    'timer.selectSession': 'Seleziona una sessione',
    'timer.homework': 'Compiti',
    'timer.study': 'Studio',
    'timer.break': 'Pausa',
    'timer.reading': 'Lettura',
    'timer.writing': 'Scrittura',
    'timer.research': 'Ricerca',
    'timer.review': 'Revisione',
    'timer.minutes': 'minuti',
    'timer.seconds': 'secondi',
    'timer.timeUp': 'Tempo scaduto!',
    'timer.sessionComplete': 'Sessione completata!',
    'timer.takeBreak': 'Prenditi una pausa',
    'timer.backToWork': 'Torna al lavoro',
    'timer.paused': 'In Pausa',
    'timer.resume': 'Riprendi',
    
    // Progress Tracker
    'progress.title': 'Tracciatore di Progresso',
    'progress.tasksCompleted': 'Compiti Completati',
    'progress.totalTasks': 'Compiti Totali',
    'progress.completionRate': 'Tasso di Completamento',
    'progress.studyTime': 'Tempo di Studio',
    'progress.thisWeek': 'Questa Settimana',
    'progress.thisMonth': 'Questo Mese',
    'progress.hours': 'ore',
    'progress.noData': 'Nessun dato disponibile',
    'progress.keepGoing': 'Continua così!',
    
    // Quick Notes
    'notes.title': 'Note Veloci',
    'notes.add': 'Aggiungi Nota',
    'notes.placeholder': 'Inizia a scrivere la tua nota...',
    'notes.save': 'Salva Nota',
    'notes.edit': 'Modifica Nota',
    'notes.delete': 'Elimina Nota',
    'notes.empty': 'Nessuna nota ancora',
    'notes.createFirst': 'Crea la tua prima nota!',
    'notes.untitled': 'Nota Senza Titolo',
    'notes.confirmDelete': 'Sei sicuro di voler eliminare questa nota?',
    'notes.deleteConfirm': 'Questa azione non può essere annullata.',
    
    // Study Links
    'links.title': 'Link di Studio',
    'links.add': 'Aggiungi Link',
    'links.name': 'Nome Link',
    'links.url': 'URL',
    'links.category': 'Categoria',
    'links.research': 'Ricerca',
    'links.reference': 'Riferimento',
    'links.tutorial': 'Tutorial',
    'links.article': 'Articolo',
    'links.video': 'Video',
    'links.other': 'Altro',
    'links.visit': 'Visita Link',
    'links.edit': 'Modifica Link',
    'links.delete': 'Elimina Link',
    'links.empty': 'Nessun link di studio ancora',
    'links.createFirst': 'Aggiungi il tuo primo link di studio!',
    
    // Task Prioritization
    'prioritization.title': 'Prioritizzazione Compiti',
    'prioritization.dragToReorder': 'Trascina i compiti per riordinare per priorità',
    'prioritization.highPriority': 'Alta Priorità',
    'prioritization.mediumPriority': 'Priorità Media',
    'prioritization.lowPriority': 'Bassa Priorità',
    'prioritization.reorderTasks': 'Riordina Compiti',
    'prioritization.empty': 'Nessun compito da prioritizzare',
    'prioritization.createTasks': 'Crea prima alcuni compiti!',
    
    // Study Mode
    'study.title': 'Modalità Studio',
    'study.focusMode': 'Modalità Focus Attiva',
    'study.exitFocus': 'Esci dalla Modalità Focus',
    'study.currentTask': 'Compito Corrente',
    'study.noActiveTask': 'Nessun compito attivo',
    'study.selectTask': 'Seleziona un compito su cui concentrarti',
    'study.timeRemaining': 'Tempo Rimanente',
    'study.sessionType': 'Tipo di Sessione',
    'study.productivity': 'Pannello di Produttività',
    'study.todaysFocus': 'Focus di Oggi',
    'study.weeklyGoal': 'Obiettivo Settimanale',
    'study.completedToday': 'Completato Oggi',
    'study.streak': 'Serie Corrente',
    'study.days': 'giorni',
    
    // AI Study Suggestions
    'ai.title': 'Suggerimenti di Studio IA',
    'ai.generating': 'Generando suggerimenti...',
    'ai.suggestions': 'Suggerimenti di Studio',
    'ai.noSuggestions': 'Nessun suggerimento disponibile',
    'ai.tryAgain': 'Riprova',
    'ai.basedOnTasks': 'Basato sui tuoi compiti attuali',
    'ai.studyPlan': 'Piano di Studio',
    'ai.recommendation': 'Raccomandazione',
    
    // Forms and Dialogs
    'form.required': 'Questo campo è obbligatorio',
    'form.cancel': 'Annulla',
    'form.save': 'Salva',
    'form.create': 'Crea',
    'form.update': 'Aggiorna',
    'form.delete': 'Elimina',
    'form.confirm': 'Conferma',
    'form.loading': 'Caricamento...',
    'form.success': 'Successo!',
    'form.error': 'Errore verificato',
    'form.tryAgain': 'Riprova',
    
    // General
    'general.loading': 'Caricamento...',
    'general.error': 'Errore',
    'general.success': 'Successo',
    'general.warning': 'Avviso',
    'general.info': 'Info',
    'general.close': 'Chiudi',
    'general.open': 'Apri',
    'general.show': 'Mostra',
    'general.hide': 'Nascondi',
    'general.more': 'Di più',
    'general.less': 'Meno',
    'general.all': 'Tutti',
    'general.none': 'Nessuno',
    'general.search': 'Cerca',
    'general.filter': 'Filtra',
    'general.sort': 'Ordina',
    'general.refresh': 'Aggiorna',
  },
  ja: {
    // Header
    'app.title': 'StudyFlow',
    'app.subtitle': 'AI搭載学生生産性',
    'header.studyMode': '学習モード',
    'header.signIn': 'サインイン',
    'header.signOut': 'サインアウト',
    'header.overdue': '期限切れ',
    'header.dueToday': '今日期限',
    
    // Main sections
    'section.tasks': 'タスク',
    'section.progress': '進捗',
    'section.timer': '集中タイマー',
    'section.studyLinks': '学習リンク',
    'section.quickNotes': 'クイックノート',
    'section.prioritization': 'タスク優先順位',
    
    // Common actions
    'action.add': '追加',
    'action.edit': '編集',
    'action.delete': '削除',
    'action.save': '保存',
    'action.cancel': 'キャンセル',
    'action.complete': '完了',
    'action.start': '開始',
    'action.pause': '一時停止',
    'action.stop': '停止',
    'action.reset': 'リセット',
    
    // Task related
    'task.new': '新しいタスク',
    'task.title': 'タスクタイトル',
    'task.description': '説明',
    'task.priority': '優先度',
    'task.dueDate': '期限',
    'task.completed': '完了',
    'task.pending': '保留中',
    'task.high': '高',
    'task.medium': '中',
    'task.low': '低',
    'task.addTask': 'タスクを追加',
    'task.noTasks': 'まだタスクがありません',
    'task.createFirst': '最初のタスクを作成して始めましょう！',
    'task.overdue': '期限切れ',
    'task.today': '今日期限',
    'task.upcoming': '今後',
    'task.completed.title': '完了したタスク',
    'task.markComplete': '完了としてマーク',
    'task.markIncomplete': '未完了としてマーク',
    'task.edit': 'タスクを編集',
    'task.delete': 'タスクを削除',
    'task.due': '期限',
    'task.noDueDate': '期限なし',
    
    // Focus Timer
    'timer.title': '集中タイマー',
    'timer.selectSession': 'セッションを選択',
    'timer.homework': '宿題',
    'timer.study': '学習',
    'timer.break': '休憩',
    'timer.reading': '読書',
    'timer.writing': '執筆',
    'timer.research': '調査',
    'timer.review': '復習',
    'timer.minutes': '分',
    'timer.seconds': '秒',
    'timer.timeUp': '時間切れ！',
    'timer.sessionComplete': 'セッション完了！',
    'timer.takeBreak': '休憩を取る',
    'timer.backToWork': '作業に戻る',
    'timer.paused': '一時停止中',
    'timer.resume': '再開',
    
    // Progress Tracker
    'progress.title': '進捗トラッカー',
    'progress.tasksCompleted': '完了したタスク',
    'progress.totalTasks': '総タスク数',
    'progress.completionRate': '完了率',
    'progress.studyTime': '学習時間',
    'progress.thisWeek': '今週',
    'progress.thisMonth': '今月',
    'progress.hours': '時間',
    'progress.noData': 'データがありません',
    'progress.keepGoing': 'その調子です！',
    
    // Quick Notes
    'notes.title': 'クイックノート',
    'notes.add': 'ノートを追加',
    'notes.placeholder': 'ノートを入力してください...',
    'notes.save': 'ノートを保存',
    'notes.edit': 'ノートを編集',
    'notes.delete': 'ノートを削除',
    'notes.empty': 'まだノートがありません',
    'notes.createFirst': '最初のノートを作成しましょう！',
    'notes.untitled': 'タイトルなし',
    'notes.confirmDelete': 'このノートを削除してもよろしいですか？',
    'notes.deleteConfirm': 'この操作は元に戻せません。',
    
    // Study Links
    'links.title': '学習リンク',
    'links.add': 'リンクを追加',
    'links.name': 'リンク名',
    'links.url': 'URL',
    'links.category': 'カテゴリ',
    'links.research': '調査',
    'links.reference': '参考',
    'links.tutorial': 'チュートリアル',
    'links.article': '記事',
    'links.video': 'ビデオ',
    'links.other': 'その他',
    'links.visit': 'リンクを訪問',
    'links.edit': 'リンクを編集',
    'links.delete': 'リンクを削除',
    'links.empty': 'まだ学習リンクがありません',
    'links.createFirst': '最初の学習リンクを追加しましょう！',
    
    // Task Prioritization
    'prioritization.title': 'タスク優先順位',
    'prioritization.dragToReorder': 'タスクをドラッグして優先順位を変更',
    'prioritization.highPriority': '高優先度',
    'prioritization.mediumPriority': '中優先度',
    'prioritization.lowPriority': '低優先度',
    'prioritization.reorderTasks': 'タスクを並び替え',
    'prioritization.empty': '優先順位を付けるタスクがありません',
    'prioritization.createTasks': 'まずタスクを作成しましょう！',
    
    // Study Mode
    'study.title': '学習モード',
    'study.focusMode': '集中モード有効',
    'study.exitFocus': '集中モードを終了',
    'study.currentTask': '現在のタスク',
    'study.noActiveTask': 'アクティブなタスクなし',
    'study.selectTask': '集中するタスクを選択',
    'study.timeRemaining': '残り時間',
    'study.sessionType': 'セッションタイプ',
    'study.productivity': '生産性ダッシュボード',
    'study.todaysFocus': '今日の集中',
    'study.weeklyGoal': '週間目標',
    'study.completedToday': '今日完了',
    'study.streak': '現在の連続',
    'study.days': '日',
    
    // AI Study Suggestions
    'ai.title': 'AI学習提案',
    'ai.generating': '提案を生成中...',
    'ai.suggestions': '学習提案',
    'ai.noSuggestions': '提案がありません',
    'ai.tryAgain': '再試行',
    'ai.basedOnTasks': '現在のタスクに基づく',
    'ai.studyPlan': '学習計画',
    'ai.recommendation': '推奨',
    
    // Forms and Dialogs
    'form.required': 'この項目は必須です',
    'form.cancel': 'キャンセル',
    'form.save': '保存',
    'form.create': '作成',
    'form.update': '更新',
    'form.delete': '削除',
    'form.confirm': '確認',
    'form.loading': '読み込み中...',
    'form.success': '成功！',
    'form.error': 'エラーが発生しました',
    'form.tryAgain': '再試行',
    
    // General
    'general.loading': '読み込み中...',
    'general.error': 'エラー',
    'general.success': '成功',
    'general.warning': '警告',
    'general.info': '情報',
    'general.close': '閉じる',
    'general.open': '開く',
    'general.show': '表示',
    'general.hide': '非表示',
    'general.more': 'その他',
    'general.less': '少ない',
    'general.all': 'すべて',
    'general.none': 'なし',
    'general.search': '検索',
    'general.filter': 'フィルター',
    'general.sort': 'ソート',
    'general.refresh': '更新',
  },
  ko: {
    // Header
    'app.title': 'StudyFlow',
    'app.subtitle': 'AI 기반 학생 생산성',
    'header.studyMode': '학습 모드',
    'header.signIn': '로그인',
    'header.signOut': '로그아웃',
    'header.overdue': '연체',
    'header.dueToday': '오늘 만료',
    
    // Main sections
    'section.tasks': '작업',
    'section.progress': '진행 상황',
    'section.timer': '집중 타이머',
    'section.studyLinks': '학습 링크',
    'section.quickNotes': '빠른 노트',
    'section.prioritization': '작업 우선순위',
    
    // Common actions
    'action.add': '추가',
    'action.edit': '편집',
    'action.delete': '삭제',
    'action.save': '저장',
    'action.cancel': '취소',
    'action.complete': '완료',
    'action.start': '시작',
    'action.pause': '일시 정지',
    'action.stop': '중지',
    'action.reset': '재설정',
    
    // Task related
    'task.new': '새 작업',
    'task.title': '작업 제목',
    'task.description': '설명',
    'task.priority': '우선순위',
    'task.dueDate': '마감일',
    'task.completed': '완료됨',
    'task.pending': '대기 중',
    'task.high': '높음',
    'task.medium': '보통',
    'task.low': '낮음',
    'task.addTask': '작업 추가',
    'task.noTasks': '아직 작업이 없습니다',
    'task.createFirst': '첫 번째 작업을 만들어 시작하세요!',
    'task.overdue': '연체',
    'task.today': '오늘 마감',
    'task.upcoming': '예정',
    'task.completed.title': '완료된 작업',
    'task.markComplete': '완료로 표시',
    'task.markIncomplete': '미완료로 표시',
    'task.edit': '작업 편집',
    'task.delete': '작업 삭제',
    'task.due': '마감',
    'task.noDueDate': '마감일 없음',
    
    // Focus Timer
    'timer.title': '집중 타이머',
    'timer.selectSession': '세션 선택',
    'timer.homework': '숙제',
    'timer.study': '학습',
    'timer.break': '휴식',
    'timer.reading': '독서',
    'timer.writing': '작성',
    'timer.research': '연구',
    'timer.review': '복습',
    'timer.minutes': '분',
    'timer.seconds': '초',
    'timer.timeUp': '시간 종료!',
    'timer.sessionComplete': '세션 완료!',
    'timer.takeBreak': '휴식을 취하세요',
    'timer.backToWork': '작업으로 돌아가기',
    'timer.paused': '일시 정지됨',
    'timer.resume': '재개',
    
    // Progress Tracker
    'progress.title': '진행 상황 추적기',
    'progress.tasksCompleted': '완료된 작업',
    'progress.totalTasks': '총 작업',
    'progress.completionRate': '완료율',
    'progress.studyTime': '학습 시간',
    'progress.thisWeek': '이번 주',
    'progress.thisMonth': '이번 달',
    'progress.hours': '시간',
    'progress.noData': '데이터 없음',
    'progress.keepGoing': '계속해서 잘하고 있어요!',
    
    // Quick Notes
    'notes.title': '빠른 노트',
    'notes.add': '노트 추가',
    'notes.placeholder': '노트를 입력하세요...',
    'notes.save': '노트 저장',
    'notes.edit': '노트 편집',
    'notes.delete': '노트 삭제',
    'notes.empty': '아직 노트가 없습니다',
    'notes.createFirst': '첫 번째 노트를 만들어보세요!',
    'notes.untitled': '제목 없음',
    'notes.confirmDelete': '이 노트를 삭제하시겠습니까?',
    'notes.deleteConfirm': '이 작업은 되돌릴 수 없습니다.',
    
    // Study Links
    'links.title': '학습 링크',
    'links.add': '링크 추가',
    'links.name': '링크 이름',
    'links.url': 'URL',
    'links.category': '카테고리',
    'links.research': '연구',
    'links.reference': '참조',
    'links.tutorial': '튜토리얼',
    'links.article': '기사',
    'links.video': '비디오',
    'links.other': '기타',
    'links.visit': '링크 방문',
    'links.edit': '링크 편집',
    'links.delete': '링크 삭제',
    'links.empty': '아직 학습 링크가 없습니다',
    'links.createFirst': '첫 번째 학습 링크를 추가하세요!',
    
    // Task Prioritization
    'prioritization.title': '작업 우선순위',
    'prioritization.dragToReorder': '작업을 드래그하여 우선순위별로 재정렬',
    'prioritization.highPriority': '높은 우선순위',
    'prioritization.mediumPriority': '보통 우선순위',
    'prioritization.lowPriority': '낮은 우선순위',
    'prioritization.reorderTasks': '작업 재정렬',
    'prioritization.empty': '우선순위를 정할 작업이 없습니다',
    'prioritization.createTasks': '먼저 작업을 만들어보세요!',
    
    // Study Mode
    'study.title': '학습 모드',
    'study.focusMode': '집중 모드 활성',
    'study.exitFocus': '집중 모드 종료',
    'study.currentTask': '현재 작업',
    'study.noActiveTask': '활성 작업 없음',
    'study.selectTask': '집중할 작업 선택',
    'study.timeRemaining': '남은 시간',
    'study.sessionType': '세션 유형',
    'study.productivity': '생산성 대시보드',
    'study.todaysFocus': '오늘의 집중',
    'study.weeklyGoal': '주간 목표',
    'study.completedToday': '오늘 완료',
    'study.streak': '현재 연속',
    'study.days': '일',
    
    // AI Study Suggestions
    'ai.title': 'AI 학습 제안',
    'ai.generating': '제안 생성 중...',
    'ai.suggestions': '학습 제안',
    'ai.noSuggestions': '제안이 없습니다',
    'ai.tryAgain': '다시 시도',
    'ai.basedOnTasks': '현재 작업 기반',
    'ai.studyPlan': '학습 계획',
    'ai.recommendation': '추천',
    
    // Forms and Dialogs
    'form.required': '이 필드는 필수입니다',
    'form.cancel': '취소',
    'form.save': '저장',
    'form.create': '생성',
    'form.update': '업데이트',
    'form.delete': '삭제',
    'form.confirm': '확인',
    'form.loading': '로딩 중...',
    'form.success': '성공!',
    'form.error': '오류 발생',
    'form.tryAgain': '다시 시도',
    
    // General
    'general.loading': '로딩 중...',
    'general.error': '오류',
    'general.success': '성공',
    'general.warning': '경고',
    'general.info': '정보',
    'general.close': '닫기',
    'general.open': '열기',
    'general.show': '표시',
    'general.hide': '숨기기',
    'general.more': '더 보기',
    'general.less': '적게',
    'general.all': '모두',
    'general.none': '없음',
    'general.search': '검색',
    'general.filter': '필터',
    'general.sort': '정렬',
    'general.refresh': '새로 고침',
  },
  zh: {
    // Header
    'app.title': 'StudyFlow',
    'app.subtitle': 'AI驱动的学生生产力',
    'header.studyMode': '学习模式',
    'header.signIn': '登录',
    'header.signOut': '退出',
    'header.overdue': '逾期',
    'header.dueToday': '今日到期',
    
    // Main sections
    'section.tasks': '任务',
    'section.progress': '进度',
    'section.timer': '专注计时器',
    'section.studyLinks': '学习链接',
    'section.quickNotes': '快速笔记',
    'section.prioritization': '任务优先级',
    
    // Common actions
    'action.add': '添加',
    'action.edit': '编辑',
    'action.delete': '删除',
    'action.save': '保存',
    'action.cancel': '取消',
    'action.complete': '完成',
    'action.start': '开始',
    'action.pause': '暂停',
    'action.stop': '停止',
    'action.reset': '重置',
    
    // Task related
    'task.new': '新任务',
    'task.title': '任务标题',
    'task.description': '描述',
    'task.priority': '优先级',
    'task.dueDate': '截止日期',
    'task.completed': '已完成',
    'task.pending': '待处理',
    'task.high': '高',
    'task.medium': '中',
    'task.low': '低',
    'task.addTask': '添加任务',
    'task.noTasks': '还没有任务',
    'task.createFirst': '创建您的第一个任务来开始！',
    'task.overdue': '逾期',
    'task.today': '今日到期',
    'task.upcoming': '即将到来',
    'task.completed.title': '已完成任务',
    'task.markComplete': '标记为完成',
    'task.markIncomplete': '标记为未完成',
    'task.edit': '编辑任务',
    'task.delete': '删除任务',
    'task.due': '到期',
    'task.noDueDate': '没有截止日期',
    
    // Focus Timer
    'timer.title': '专注计时器',
    'timer.selectSession': '选择会话',
    'timer.homework': '作业',
    'timer.study': '学习',
    'timer.break': '休息',
    'timer.reading': '阅读',
    'timer.writing': '写作',
    'timer.research': '研究',
    'timer.review': '复习',
    'timer.minutes': '分钟',
    'timer.seconds': '秒',
    'timer.timeUp': '时间到！',
    'timer.sessionComplete': '会话完成！',
    'timer.takeBreak': '休息一下',
    'timer.backToWork': '回到工作',
    'timer.paused': '已暂停',
    'timer.resume': '继续',
    
    // Progress Tracker
    'progress.title': '进度追踪器',
    'progress.tasksCompleted': '已完成任务',
    'progress.totalTasks': '总任务',
    'progress.completionRate': '完成率',
    'progress.studyTime': '学习时间',
    'progress.thisWeek': '本周',
    'progress.thisMonth': '本月',
    'progress.hours': '小时',
    'progress.noData': '没有数据',
    'progress.keepGoing': '继续保持！',
    
    // Quick Notes
    'notes.title': '快速笔记',
    'notes.add': '添加笔记',
    'notes.placeholder': '开始输入您的笔记...',
    'notes.save': '保存笔记',
    'notes.edit': '编辑笔记',
    'notes.delete': '删除笔记',
    'notes.empty': '还没有笔记',
    'notes.createFirst': '创建您的第一个笔记！',
    'notes.untitled': '无标题笔记',
    'notes.confirmDelete': '您确定要删除这个笔记吗？',
    'notes.deleteConfirm': '此操作无法撤消。',
    
    // Study Links
    'links.title': '学习链接',
    'links.add': '添加链接',
    'links.name': '链接名称',
    'links.url': 'URL',
    'links.category': '类别',
    'links.research': '研究',
    'links.reference': '参考',
    'links.tutorial': '教程',
    'links.article': '文章',
    'links.video': '视频',
    'links.other': '其他',
    'links.visit': '访问链接',
    'links.edit': '编辑链接',
    'links.delete': '删除链接',
    'links.empty': '还没有学习链接',
    'links.createFirst': '添加您的第一个学习链接！',
    
    // Task Prioritization
    'prioritization.title': '任务优先级',
    'prioritization.dragToReorder': '拖动任务以按优先级重新排序',
    'prioritization.highPriority': '高优先级',
    'prioritization.mediumPriority': '中优先级',
    'prioritization.lowPriority': '低优先级',
    'prioritization.reorderTasks': '重新排序任务',
    'prioritization.empty': '没有任务需要优先级排序',
    'prioritization.createTasks': '首先创建一些任务！',
    
    // Study Mode
    'study.title': '学习模式',
    'study.focusMode': '专注模式激活',
    'study.exitFocus': '退出专注模式',
    'study.currentTask': '当前任务',
    'study.noActiveTask': '没有活动任务',
    'study.selectTask': '选择要专注的任务',
    'study.timeRemaining': '剩余时间',
    'study.sessionType': '会话类型',
    'study.productivity': '生产力仪表板',
    'study.todaysFocus': '今天的专注',
    'study.weeklyGoal': '周目标',
    'study.completedToday': '今天完成',
    'study.streak': '当前连续',
    'study.days': '天',
    
    // AI Study Suggestions
    'ai.title': 'AI学习建议',
    'ai.generating': '正在生成建议...',
    'ai.suggestions': '学习建议',
    'ai.noSuggestions': '没有建议',
    'ai.tryAgain': '再试一次',
    'ai.basedOnTasks': '基于您当前的任务',
    'ai.studyPlan': '学习计划',
    'ai.recommendation': '推荐',
    
    // Forms and Dialogs
    'form.required': '此字段是必需的',
    'form.cancel': '取消',
    'form.save': '保存',
    'form.create': '创建',
    'form.update': '更新',
    'form.delete': '删除',
    'form.confirm': '确认',
    'form.loading': '加载中...',
    'form.success': '成功！',
    'form.error': '发生错误',
    'form.tryAgain': '再试一次',
    
    // General
    'general.loading': '加载中...',
    'general.error': '错误',
    'general.success': '成功',
    'general.warning': '警告',
    'general.info': '信息',
    'general.close': '关闭',
    'general.open': '打开',
    'general.show': '显示',
    'general.hide': '隐藏',
    'general.more': '更多',
    'general.less': '更少',
    'general.all': '全部',
    'general.none': '无',
    'general.search': '搜索',
    'general.filter': '过滤',
    'general.sort': '排序',
    'general.refresh': '刷新',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('studyflow-language');
    return (saved as Language) || 'en';
  });

  useEffect(() => {
    localStorage.setItem('studyflow-language', language);
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}