// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kofbhggloaapndnuhmsc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtvZmJoZ2dsb2FhcG5kbnVobXNjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1MDcxMDYsImV4cCI6MjA2ODA4MzEwNn0.ORLPL24zaSFTpzLiOIBuuDTkpMX8jsbqfb4JpAaZ8-A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});